// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using XamarinAzureAD.RestServices.SipEntities.Models;

namespace XamarinAzureAD.RestServices.SipEntities
{
    public partial interface ILogin
    {
        /// <param name='refreshToken'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<LoginAuthResponse>> LoginTokenWithOperationResponseAsync(string refreshToken, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='username'>
        /// Required.
        /// </param>
        /// <param name='password'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<LoginAuthResponse>> LoginUsernamePasswordWithOperationResponseAsync(string username, string password, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
