// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using XamarinAzureAD.RestServices.SipEntities;
using XamarinAzureAD.RestServices.SipEntities.Models;

namespace XamarinAzureAD.RestServices.SipEntities
{
    public static partial class LoginExtensions
    {
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.RestServices.SipEntities.ILogin.
        /// </param>
        /// <param name='refreshToken'>
        /// Required.
        /// </param>
        public static LoginAuthResponse LoginToken(this ILogin operations, string refreshToken)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ILogin)s).LoginTokenAsync(refreshToken);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.RestServices.SipEntities.ILogin.
        /// </param>
        /// <param name='refreshToken'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<LoginAuthResponse> LoginTokenAsync(this ILogin operations, string refreshToken, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<XamarinAzureAD.RestServices.SipEntities.Models.LoginAuthResponse> result = await operations.LoginTokenWithOperationResponseAsync(refreshToken, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.RestServices.SipEntities.ILogin.
        /// </param>
        /// <param name='username'>
        /// Required.
        /// </param>
        /// <param name='password'>
        /// Required.
        /// </param>
        public static LoginAuthResponse LoginUsernamePassword(this ILogin operations, string username, string password)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ILogin)s).LoginUsernamePasswordAsync(username, password);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.RestServices.SipEntities.ILogin.
        /// </param>
        /// <param name='username'>
        /// Required.
        /// </param>
        /// <param name='password'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<LoginAuthResponse> LoginUsernamePasswordAsync(this ILogin operations, string username, string password, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<XamarinAzureAD.RestServices.SipEntities.Models.LoginAuthResponse> result = await operations.LoginUsernamePasswordWithOperationResponseAsync(username, password, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
