// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using MobileApi.RestServices.SipEntities;
using MobileApi.RestServices.SipEntities.Models;

namespace MobileApi.RestServices.SipEntities
{
    public static partial class UsersExtensions
    {
        /// <param name='operations'>
        /// Reference to the MobileApi.RestServices.SipEntities.IUsers.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        public static IList<User> Get(this IUsers operations, LoginAuthRequest request)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IUsers)s).GetAsync(request);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MobileApi.RestServices.SipEntities.IUsers.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<User>> GetAsync(this IUsers operations, LoginAuthRequest request, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<MobileApi.RestServices.SipEntities.Models.User>> result = await operations.GetWithOperationResponseAsync(request, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MobileApi.RestServices.SipEntities.IUsers.
        /// </param>
        /// <param name='loginRequest'>
        /// Required.
        /// </param>
        public static LoginAuthResponse Login(this IUsers operations, LoginAuthRequest loginRequest)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IUsers)s).LoginAsync(loginRequest);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MobileApi.RestServices.SipEntities.IUsers.
        /// </param>
        /// <param name='loginRequest'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<LoginAuthResponse> LoginAsync(this IUsers operations, LoginAuthRequest loginRequest, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<MobileApi.RestServices.SipEntities.Models.LoginAuthResponse> result = await operations.LoginWithOperationResponseAsync(loginRequest, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
