// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using XamarinAzureAD.RestServices.SipEntities;
using XamarinAzureAD.RestServices.SipEntities.Models;

namespace XamarinAzureAD.RestServices.SipEntities
{
    public static partial class UsersExtensions
    {
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.RestServices.SipEntities.IUsers.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        public static IList<ADUser> Get(this IUsers operations, LoginAuthRequest request)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IUsers)s).GetAsync(request);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.RestServices.SipEntities.IUsers.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<ADUser>> GetAsync(this IUsers operations, LoginAuthRequest request, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<XamarinAzureAD.RestServices.SipEntities.Models.ADUser>> result = await operations.GetWithOperationResponseAsync(request, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
