// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using XamarinAzureAD.Droid.Models;

namespace XamarinAzureAD.Droid
{
    public partial interface INewsOperations
    {
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='token'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<News>>> GetNewsWithOperationResponseAsync(string id, string token, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
