// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using XamarinAzureAD.Droid;
using XamarinAzureAD.Droid.Models;

namespace XamarinAzureAD.Droid
{
    public static partial class LoginExtensions
    {
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.Droid.ILogin.
        /// </param>
        /// <param name='refreshToken'>
        /// Required.
        /// </param>
        public static AuthenticationResult GetByToken(this ILogin operations, string refreshToken)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ILogin)s).GetByTokenAsync(refreshToken);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.Droid.ILogin.
        /// </param>
        /// <param name='refreshToken'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<AuthenticationResult> GetByTokenAsync(this ILogin operations, string refreshToken, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<XamarinAzureAD.Droid.Models.AuthenticationResult> result = await operations.GetByTokenWithOperationResponseAsync(refreshToken, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.Droid.ILogin.
        /// </param>
        /// <param name='username'>
        /// Required.
        /// </param>
        /// <param name='password'>
        /// Required.
        /// </param>
        public static AuthenticationResult GetByUsernamePassword(this ILogin operations, string username, string password)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ILogin)s).GetByUsernamePasswordAsync(username, password);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.Droid.ILogin.
        /// </param>
        /// <param name='username'>
        /// Required.
        /// </param>
        /// <param name='password'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<AuthenticationResult> GetByUsernamePasswordAsync(this ILogin operations, string username, string password, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<XamarinAzureAD.Droid.Models.AuthenticationResult> result = await operations.GetByUsernamePasswordWithOperationResponseAsync(username, password, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
