// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using XamarinAzureAD.Droid;

namespace XamarinAzureAD.Droid
{
    public partial class NativeWebApi : ServiceClient<NativeWebApi>, INativeWebApi
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private ILogin _login;
        
        public virtual ILogin Login
        {
            get { return this._login; }
        }
        
        private INewsOperations _news;
        
        public virtual INewsOperations News
        {
            get { return this._news; }
        }
        
        private IValues _values;
        
        public virtual IValues Values
        {
            get { return this._values; }
        }
        
        /// <summary>
        /// Initializes a new instance of the NativeWebApi class.
        /// </summary>
        public NativeWebApi()
            : base()
        {
            this._login = new Login(this);
            this._news = new NewsOperations(this);
            this._values = new Values(this);
            this._baseUri = new Uri("https://microsoft-apiappc1f91447b91f4dc3834cbde4fca6a49c.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the NativeWebApi class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public NativeWebApi(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._login = new Login(this);
            this._news = new NewsOperations(this);
            this._values = new Values(this);
            this._baseUri = new Uri("https://microsoft-apiappc1f91447b91f4dc3834cbde4fca6a49c.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the NativeWebApi class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public NativeWebApi(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._login = new Login(this);
            this._news = new NewsOperations(this);
            this._values = new Values(this);
            this._baseUri = new Uri("https://microsoft-apiappc1f91447b91f4dc3834cbde4fca6a49c.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the NativeWebApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public NativeWebApi(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the NativeWebApi class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public NativeWebApi(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the NativeWebApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public NativeWebApi(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
