// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace XamarinAzureAD.Droid.Models
{
    public partial class News
    {
        private string _description;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private string _header;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Header
        {
            get { return this._header; }
            set { this._header = value; }
        }
        
        private string _pictureUri;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PictureUri
        {
            get { return this._pictureUri; }
            set { this._pictureUri = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the News class.
        /// </summary>
        public News()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken headerValue = inputObject["Header"];
                if (headerValue != null && headerValue.Type != JTokenType.Null)
                {
                    this.Header = ((string)headerValue);
                }
                JToken pictureUriValue = inputObject["PictureUri"];
                if (pictureUriValue != null && pictureUriValue.Type != JTokenType.Null)
                {
                    this.PictureUri = ((string)pictureUriValue);
                }
            }
        }
    }
}
