// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using XamarinAzureAD.iOS;
using XamarinAzureAD.iOS.Models;

namespace XamarinAzureAD.iOS
{
    public static partial class NewsOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.iOS.INewsOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='token'>
        /// Required.
        /// </param>
        public static IList<News> GetNews(this INewsOperations operations, string id, string token)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((INewsOperations)s).GetNewsAsync(id, token);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the XamarinAzureAD.iOS.INewsOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='token'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<News>> GetNewsAsync(this INewsOperations operations, string id, string token, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<XamarinAzureAD.iOS.Models.News>> result = await operations.GetNewsWithOperationResponseAsync(id, token, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
