// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace XamarinAzureAD.RestServices.SipEntities.Models
{
    public partial class ADUser
    {
        private string _firstName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FirstName
        {
            get { return this._firstName; }
            set { this._firstName = value; }
        }
        
        private string _givenName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string GivenName
        {
            get { return this._givenName; }
            set { this._givenName = value; }
        }
        
        private string _location;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Location
        {
            get { return this._location; }
            set { this._location = value; }
        }
        
        private string _surName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SurName
        {
            get { return this._surName; }
            set { this._surName = value; }
        }
        
        private string _telephoneNumber;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string TelephoneNumber
        {
            get { return this._telephoneNumber; }
            set { this._telephoneNumber = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ADUser class.
        /// </summary>
        public ADUser()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken firstNameValue = inputObject["FirstName"];
                if (firstNameValue != null && firstNameValue.Type != JTokenType.Null)
                {
                    this.FirstName = ((string)firstNameValue);
                }
                JToken givenNameValue = inputObject["GivenName"];
                if (givenNameValue != null && givenNameValue.Type != JTokenType.Null)
                {
                    this.GivenName = ((string)givenNameValue);
                }
                JToken locationValue = inputObject["Location"];
                if (locationValue != null && locationValue.Type != JTokenType.Null)
                {
                    this.Location = ((string)locationValue);
                }
                JToken surNameValue = inputObject["SurName"];
                if (surNameValue != null && surNameValue.Type != JTokenType.Null)
                {
                    this.SurName = ((string)surNameValue);
                }
                JToken telephoneNumberValue = inputObject["TelephoneNumber"];
                if (telephoneNumberValue != null && telephoneNumberValue.Type != JTokenType.Null)
                {
                    this.TelephoneNumber = ((string)telephoneNumberValue);
                }
            }
        }
    }
}
