// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace XamarinAzureAD.RestServices.SipEntities.Models
{
    public partial class LoginAuthRequest
    {
        private string _accessToken;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AccessToken
        {
            get { return this._accessToken; }
            set { this._accessToken = value; }
        }
        
        private string _refreshToken;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RefreshToken
        {
            get { return this._refreshToken; }
            set { this._refreshToken = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the LoginAuthRequest class.
        /// </summary>
        public LoginAuthRequest()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type LoginAuthRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.AccessToken != null)
            {
                outputObject["AccessToken"] = this.AccessToken;
            }
            if (this.RefreshToken != null)
            {
                outputObject["RefreshToken"] = this.RefreshToken;
            }
            return outputObject;
        }
    }
}
