// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;
using XamarinAzureAD.iOS.Models;

namespace XamarinAzureAD.iOS.Models
{
    public partial class AuthenticationResult
    {
        private string _accessToken;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AccessToken
        {
            get { return this._accessToken; }
            set { this._accessToken = value; }
        }
        
        private string _accessTokenType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AccessTokenType
        {
            get { return this._accessTokenType; }
            set { this._accessTokenType = value; }
        }
        
        private DateTimeOffset? _expiresOn;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ExpiresOn
        {
            get { return this._expiresOn; }
            set { this._expiresOn = value; }
        }
        
        private string _idToken;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string IdToken
        {
            get { return this._idToken; }
            set { this._idToken = value; }
        }
        
        private bool? _isMultipleResourceRefreshToken;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsMultipleResourceRefreshToken
        {
            get { return this._isMultipleResourceRefreshToken; }
            set { this._isMultipleResourceRefreshToken = value; }
        }
        
        private string _refreshToken;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RefreshToken
        {
            get { return this._refreshToken; }
            set { this._refreshToken = value; }
        }
        
        private string _tenantId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string TenantId
        {
            get { return this._tenantId; }
            set { this._tenantId = value; }
        }
        
        private UserInfo _userInfo;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public UserInfo UserInfo
        {
            get { return this._userInfo; }
            set { this._userInfo = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AuthenticationResult class.
        /// </summary>
        public AuthenticationResult()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken accessTokenValue = inputObject["AccessToken"];
                if (accessTokenValue != null && accessTokenValue.Type != JTokenType.Null)
                {
                    this.AccessToken = ((string)accessTokenValue);
                }
                JToken accessTokenTypeValue = inputObject["AccessTokenType"];
                if (accessTokenTypeValue != null && accessTokenTypeValue.Type != JTokenType.Null)
                {
                    this.AccessTokenType = ((string)accessTokenTypeValue);
                }
                JToken expiresOnValue = inputObject["ExpiresOn"];
                if (expiresOnValue != null && expiresOnValue.Type != JTokenType.Null)
                {
                    this.ExpiresOn = ((DateTimeOffset)expiresOnValue);
                }
                JToken idTokenValue = inputObject["IdToken"];
                if (idTokenValue != null && idTokenValue.Type != JTokenType.Null)
                {
                    this.IdToken = ((string)idTokenValue);
                }
                JToken isMultipleResourceRefreshTokenValue = inputObject["IsMultipleResourceRefreshToken"];
                if (isMultipleResourceRefreshTokenValue != null && isMultipleResourceRefreshTokenValue.Type != JTokenType.Null)
                {
                    this.IsMultipleResourceRefreshToken = ((bool)isMultipleResourceRefreshTokenValue);
                }
                JToken refreshTokenValue = inputObject["RefreshToken"];
                if (refreshTokenValue != null && refreshTokenValue.Type != JTokenType.Null)
                {
                    this.RefreshToken = ((string)refreshTokenValue);
                }
                JToken tenantIdValue = inputObject["TenantId"];
                if (tenantIdValue != null && tenantIdValue.Type != JTokenType.Null)
                {
                    this.TenantId = ((string)tenantIdValue);
                }
                JToken userInfoValue = inputObject["UserInfo"];
                if (userInfoValue != null && userInfoValue.Type != JTokenType.Null)
                {
                    UserInfo userInfo = new UserInfo();
                    userInfo.DeserializeJson(userInfoValue);
                    this.UserInfo = userInfo;
                }
            }
        }
    }
}
